# Generated by Django 5.0.3 on 2024-03-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congratulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64, verbose_name='Автор ')),
                ('text', models.TextField(verbose_name='Текст поздравления')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='congratulations/', verbose_name='Фотография к поздравлению')),
            ],
        ),
        migrations.CreateModel(
            name='Memories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст воспоминания')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='memory_photo/')),
            ],
        ),
    ]
